name: courtfilechat_flutter
description: CourtFile Chat Application

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.7
  cloud_firestore: ^0.8.1
  # image_picker: ^0.4.10
  firestore_ui: ^1.0.1
  google_sign_in: ^3.0.5
  firebase_auth: ^0.5.20
  firebase_database: ^1.0.4
  firebase_storage: ^1.0.3
  quiver: '>=0.24.0 <0.30.0'
  http: ^0.11.3+17
  shared_preferences: ^0.4.2
  flutter_toast_pk: ^0.0.1
  timezone: ^0.5.0-dev-3
  cached_network_image: ^0.4.2
  uuid: ^1.0.3
  test: 1.3.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  common:
      path: ../common

dependency_overrides:
  quiver: '2.0.0+1'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^3.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - images/login_background.png
      - images/google.png
      - images/app_icon.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
